net_params:
  ENC_EMB_DIM: 300
  DEC_EMB_DIM: 300
  HID_DIM: 512
  N_LAYERS: 4
  ENC_DROPOUT: 0.5
  DEC_DROPOUT: 0.5
split_ration:
  train_size: 0.8
  valid_size: 0.15
  test_size: 0.05
dataset_path: 'datasets/Machine_translation_EN_RU/data.txt'
BATCH_SIZE: 1024
N_EPOCHS: 20
CLIP: 1
model_out_name: tut3-model.pt
lr: 0.001
lr_scheduler:
  mode: 'min'
  factor: 0.2
  patience: 2
  threshold: 0.01
