net_params:
  ENC_EMB_DIM: 256
  DEC_EMB_DIM: 256
  HID_DIM: 512
  N_LAYERS: 2
  ENC_DROPOUT: 0.5
  DEC_DROPOUT: 0.5
split_ration:
  train_size: 0.8
  valid_size: 0.15
  test_size: 0.05
dataset_path: '../../datasets/Machine_translation_EN_RU/data.txt'
BATCH_SIZE: 64
N_EPOCHS: 5
CLIP: 1
lr: 0.001
lr_scheduler:
  mode: 'min'
  factor: 0.2
  patience: 2
  threshold: 0.01